#!/bin/bash
# Usage ./init-db [dbname]

DB=$1
if [[ -z $1 ]]; then
    DB="chatd_log.db"
fi

SQL="
CREATE TABLE users (
    id INTEGER PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE chat_log (
    id INTEGER PRIMARY KEY,
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    room VARCHAR(255) NOT NULL,
    message TEXT
);
"

sqlite3 $DB "$SQL"
